"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 10:34:32.686286
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('tg11_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tg11_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_provider_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('secret_blob', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('secret_hint', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('default_model', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_message', sa.String(length=300), nullable=False),
    sa.Column('models_cache_json', sa.Text(), nullable=False),
    sa.Column('models_cached_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_ai_cred_user_provider')
    )
    with op.batch_alter_table('ai_provider_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_ai_cred_user', ['user_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_kind', sa.String(length=40), nullable=False),
    sa.Column('error_message', sa.String(length=300), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=False),
    sa.Column('response_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index('ix_ai_usage_board', ['board_id'], unique=False)
        batch_op.create_index('ix_ai_usage_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('boards',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('theme_json', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_board_owner_slug')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_owner_id'), ['owner_id'], unique=False)

    op.create_table('calendar_connections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('account_email', sa.String(length=254), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('token_blob', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('target_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('target_calendar_name', sa.String(length=255), nullable=False),
    sa.Column('calendars_cache_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_message', sa.String(length=300), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.create_index('ix_calconn_user', ['user_id'], unique=False)

    op.create_table('identity_links',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email_at_link', sa.String(length=254), nullable=False),
    sa.Column('username_at_link', sa.String(length=80), nullable=False),
    sa.Column('migration_source', sa.String(length=64), nullable=False),
    sa.Column('migration_status', sa.String(length=32), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.create_index('ix_identity_links_user', ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_board_id', sa.String(length=36), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('work_day_minutes', sa.Integer(), nullable=False),
    sa.Column('default_ai_model', sa.String(length=200), nullable=False),
    sa.Column('ai_fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_fallback_model', sa.String(length=200), nullable=False),
    sa.Column('ai_auto_tag_on_create', sa.Boolean(), nullable=False),
    sa.Column('ai_usage_tracking', sa.Boolean(), nullable=False),
    sa.Column('calendar_default_connection_id', sa.String(length=36), nullable=True),
    sa.Column('calendar_default_duration_min', sa.Integer(), nullable=False),
    sa.Column('board_defaults_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('ai_change_sets',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_ref', sa.String(length=200), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=False),
    sa.Column('operations_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_change_sets', schema=None) as batch_op:
        batch_op.create_index('ix_changeset_board_status', ['board_id', 'status'], unique=False)

    op.create_table('board_memberships',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'user_id', name='uq_membership_board_user')
    )
    with op.batch_alter_table('board_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_membership_user', ['user_id'], unique=False)

    op.create_table('calendar_feed_tokens',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('include_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'user_id', name='uq_feed_board_user'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('task_activity',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_kind', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_board_time', ['board_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_activity_task_id'), ['task_id'], unique=False)

    op.create_table('tasks',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('legacy_id', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimate_min', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('energy', sa.String(length=8), nullable=False),
    sa.Column('due', sa.String(length=20), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('contexts_json', sa.Text(), nullable=False),
    sa.Column('depends_on_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('manual_order', sa.Integer(), nullable=False),
    sa.Column('last_actual_min', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_board_done', ['board_id', 'done'], unique=False)
        batch_op.create_index('ix_tasks_board_due', ['board_id', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)

    op.create_table('calendar_event_links',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('external_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('sync_direction', sa.String(length=16), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'connection_id', name='uq_eventlink_task_connection')
    )
    with op.batch_alter_table('calendar_event_links', schema=None) as batch_op:
        batch_op.create_index('ix_eventlink_board', ['board_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event_links', schema=None) as batch_op:
        batch_op.drop_index('ix_eventlink_board')

    op.drop_table('calendar_event_links')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_legacy_id'))
        batch_op.drop_index('ix_tasks_board_due')
        batch_op.drop_index('ix_tasks_board_done')

    op.drop_table('tasks')
    with op.batch_alter_table('task_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_activity_task_id'))
        batch_op.drop_index('ix_activity_board_time')

    op.drop_table('task_activity')
    op.drop_table('calendar_feed_tokens')
    with op.batch_alter_table('board_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_user')

    op.drop_table('board_memberships')
    with op.batch_alter_table('ai_change_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_changeset_board_status')

    op.drop_table('ai_change_sets')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.drop_index('ix_identity_links_user')

    op.drop_table('identity_links')
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_calconn_user')

    op.drop_table('calendar_connections')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_owner_id'))

    op.drop_table('boards')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_usage_user_time')
        batch_op.drop_index('ix_ai_usage_board')

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_provider_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_cred_user')

    op.drop_table('ai_provider_credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
