"""reflections, scheduling, instructions, profile schedule

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 19:49:17.615779
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reflections',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('estimate_min', sa.Integer(), nullable=False),
    sa.Column('actual_min', sa.Integer(), nullable=True),
    sa.Column('planned_energy', sa.String(length=8), nullable=False),
    sa.Column('actual_energy', sa.String(length=8), nullable=True),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('had_instructions', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_reflections', schema=None) as batch_op:
        batch_op.create_index('ix_reflection_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_reflections_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rollover_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_tasks_scheduled_date'), ['scheduled_date'], unique=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_schedule_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('calibration_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('tutorial_seeded', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('tg11_vault_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('tg11_vault_synced_at')
        batch_op.drop_column('tutorial_seeded')
        batch_op.drop_column('calibration_json')
        batch_op.drop_column('work_schedule_json')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_scheduled_date'))
        batch_op.drop_column('instructions')
        batch_op.drop_column('rollover_count')
        batch_op.drop_column('scheduled_date')

    with op.batch_alter_table('task_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_reflections_task_id'))
        batch_op.drop_index('ix_reflection_user_time')

    op.drop_table('task_reflections')
    # ### end Alembic commands ###
