"""reflections, scheduling, instructions, profile schedule

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 19:49:17.615779
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def _cols(table: str) -> set:
    bind = op.get_bind()
    return {r[1] for r in bind.exec_driver_sql(f"PRAGMA table_info({table})")}


def _add(table: str, col: sa.Column) -> None:
    """Plain ALTER TABLE ADD COLUMN (no table rebuild - SQLite batch mode would
    re-create the table and trip over dangling foreign keys in old rows)."""
    if col.name not in _cols(table):
        op.add_column(table, col)


def upgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql("DROP TABLE IF EXISTS _alembic_tmp_user_profiles")
    if not bind.dialect.has_table(bind, "task_reflections"):
        op.create_table('task_reflections',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('estimate_min', sa.Integer(), nullable=False),
    sa.Column('actual_min', sa.Integer(), nullable=True),
    sa.Column('planned_energy', sa.String(length=8), nullable=False),
    sa.Column('actual_energy', sa.String(length=8), nullable=True),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('had_instructions', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    bind.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_reflection_user_time ON task_reflections (user_id, created_at)")
    bind.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_task_reflections_task_id ON task_reflections (task_id)")

    _add('tasks', sa.Column('scheduled_date', sa.Date(), nullable=True))
    _add('tasks', sa.Column('rollover_count', sa.Integer(), nullable=False, server_default='0'))
    _add('tasks', sa.Column('instructions', sa.Text(), nullable=False, server_default=''))
    bind.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_tasks_scheduled_date ON tasks (scheduled_date)")

    _add('user_profiles', sa.Column('work_schedule_json', sa.Text(), nullable=False, server_default='{}'))
    _add('user_profiles', sa.Column('calibration_json', sa.Text(), nullable=False, server_default='{}'))
    _add('user_profiles', sa.Column('tutorial_seeded', sa.Boolean(), nullable=False, server_default=sa.false()))
    _add('user_profiles', sa.Column('tg11_vault_synced_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('tg11_vault_synced_at')
        batch_op.drop_column('tutorial_seeded')
        batch_op.drop_column('calibration_json')
        batch_op.drop_column('work_schedule_json')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_scheduled_date'))
        batch_op.drop_column('instructions')
        batch_op.drop_column('rollover_count')
        batch_op.drop_column('scheduled_date')

    with op.batch_alter_table('task_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_reflections_task_id'))
        batch_op.drop_index('ix_reflection_user_time')

    op.drop_table('task_reflections')
    # ### end Alembic commands ###
